title: storm`s Blog
description: "System Hacking & Security Research"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: storm85851@ajou.ac.kr
github_username: storm-0rigin
twitter_username:
instagram_username: jd.11.12
linkedin_username:
facebook_username:

# External API
giscus_repo:
giscus_repoId:
giscus_category:
giscus_categoryId:
goatcounter_code:
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator
kramdown:
  input: GFM
  hard_wrap: true
